### ISSUE TITLE
Logging in as Broker produces error on Console deployment

### ISSUE THREAD

**Issue by hutch77** [DennisRSI/AdminBrokerClientAgentPortal#157]
https://www.awesomescreenshot.com/image/3481464/1910d9937c59ed3cf271112162d75962

As an Admin, I created a password for broker Scott Brunnenmeyer: sbrunnenmeyer@vacmail.com

When I went to log in using those credentials, I got the error screenshotted above

**Comment by patricksheedy** [comment]
@hutch77 Can you try this again in a different browser? I've gotten an error when I've tried to switch accounts, probably due to incorrect authentication cookies. If it is still a problem send me the password on Skype and I can try it out.

**Comment by patricksheedy** [comment]
My guess is that you are seeing this because the server is serving http pages. The login cookies are set to secure-only so they don't get sent on the http version of the site. I get an error if I go to the http version and try to login. Then if I manually change it to https I am able to login.

The best solution is to have the server redirect http connections to https. @DennisRSI can confirm if this can be implemented.

**Comment by patricksheedy** [comment]
Dennis will see if this is possible to do at the network layer.

**Comment by patricksheedy** [comment]
This user also didn't have a role assigned. I added the role in the database. Once the new build is deployed the user should be able to login.

**Comment by patricksheedy** [comment]
The QA server was missing an https binding. Once I added this the http --> https started working. This will be pushed to production in the next update.
