### ISSUE TITLE
Ron White broker not displaying Commission rate in Edit view

### ISSUE THREAD

**Issue by hutch77** [DennisRSI/AdminBrokerClientAgentPortal#166]
Broker list shows commission rate (50) but when clicking through to Ron White, commission rate is listed as 0.00. This does not happen on other brokers.

**Comment by patricksheedy** [comment]
The problem was that there was a client that had the same ApplicationReference. So on the profile screen when the code went to get the CommissionRate it was pulling the data from the Client instead of the broker. I'm not sure how the data would have gotten into that state. But I've fixed it for now in production.
